DWeb_MVC-master/DWeb_MVC/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DWeb_MVC.Data;
using DWeb_MVC.Models;
using Microsoft.AspNetCore.Authorization;

namespace DWeb_MVC.Controllers
{

    public class ClientesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClientesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Clientes
        public async Task<IActionResult> Index()
        {
              return _context.Clientes != null ? 
                          View(await _context.Clientes.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Clientes'  is null.");
        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Clientes == null)
            {
                return NotFound();
            }

            var clientes = await _context.Clientes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (clientes == null)
            {
                return NotFound();
            }

            return View(clientes);
        }

        // GET: Clientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Telemovel,Email,Morada,CodPostal")] Clientes clientes)
        {
            if (ModelState.IsValid)
            {
                _context.Add(clientes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(clientes);
        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Clientes == null)
            {
                return NotFound();
            }

            var clientes = await _context.Clientes.FindAsync(id);
            if (clientes == null)
            {
                return NotFound();
            }
            return View(clientes);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Telemovel,Email,Morada,CodPostal")] Clientes clientes)
        {
            if (id != clientes.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(clientes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientesExists(clientes.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(clientes);
        }

        // GET: Clientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Clientes == null)
            {
                return NotFound();
            }

            var clientes = await _context.Clientes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (clientes == null)
            {
                return NotFound();
            }

            return View(clientes);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Clientes == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Clientes'  is null.");
            }
            var clientes = await _context.Clientes.FindAsync(id);
            if (clientes != null)
            {
                _context.Clientes.Remove(clientes);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientesExists(int id)
        {
          return (_context.Clientes?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

DWeb_MVC-master/DWeb_MVC/Controllers/ComprasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DWeb_MVC.Data;
using DWeb_MVC.Models;

namespace DWeb_MVC.Controllers
{
    public class ComprasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ComprasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Compras
        public async Task<IActionResult> Index()
        {
            return _context.Compras != null ?
                        View(await _context.Compras.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Compras' is null.");
        }

        // GET: Compras/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Compras == null)
            {
                return NotFound();
            }

            var compras = await _context.Compras
                .FirstOrDefaultAsync(m => m.Id == id);
            if (compras == null)
            {
                return NotFound();
            }

            return View(compras);
        }

        // GET: Compras/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Compras/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Email,ProdutosComprados,PrecoTotal,QuantidadeTotal,DataCompra")] Compras compras)
        {
            if (ModelState.IsValid)
            {
                _context.Add(compras);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(compras);
        }

        // GET: Compras/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Compras == null)
            {
                return NotFound();
            }

            var compras = await _context.Compras.FindAsync(id);
            if (compras == null)
            {
                return NotFound();
            }
            return View(compras);
        }

        // POST: Compras/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Email,ProdutosComprados,PrecoTotal,QuantidadeTotal,DataCompra")] Compras compras)
        {
            if (id != compras.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(compras);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ComprasExists(compras.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(compras);
        }

        // GET: Compras/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Compras == null)
            {
                return NotFound();
            }

            var compras = await _context.Compras
                .FirstOrDefaultAsync(m => m.Id == id);
            if (compras == null)
            {
                return NotFound();
            }

            return View(compras);
        }

        // POST: Compras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Compras == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Compras' is null.");
            }
            var compras = await _context.Compras.FindAsync(id);
            if (compras != null)
            {
                _context.Compras.Remove(compras);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ComprasExists(int id)
        {
            return (_context.Compras?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

DWeb_MVC-master/DWeb_MVC/Controllers/CoresController.cs
using DWeb_MVC.Data;
using DWeb_MVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace DWeb_MVC.Controllers
{
    [Authorize(Roles = "admin")]

    public class CoresController : Controller
    {
        private readonly ApplicationDbContext _context;

        

        public CoresController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Cores.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var cor = await _context.Cores
                .Include(c => c.ListaProdutos)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (cor == null) return NotFound();

            return View(cor);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome")] Cores cor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cor);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var cor = await _context.Cores.FindAsync(id);
            if (cor == null) return NotFound();

            return View(cor);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome")] Cores cor)
        {
            if (id != cor.Id) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CoresExists(cor.Id)) return NotFound();
                    else throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cor);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var cor = await _context.Cores.FirstOrDefaultAsync(m => m.Id == id);
            if (cor == null) return NotFound();

            return View(cor);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cor = await _context.Cores
                .Include(c => c.ListaProdutos)
                .FirstOrDefaultAsync(c => c.Id == id);

            if (cor != null && cor.ListaProdutos.Any())
            {
                ModelState.AddModelError("", "Não é possível remover esta cor pois está associada a produtos.");
                return View(cor);
            }

            _context.Cores.Remove(cor);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CoresExists(int id)
        {
            return _context.Cores.Any(e => e.Id == id);
        }
    }
}

DWeb_MVC-master/DWeb_MVC/Controllers/GruposController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DWeb_MVC.Data;
using DWeb_MVC.Models;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Authorization;

namespace DWeb_MVC.Controllers
{
    [Authorize(Roles ="admin")]
    public class GruposController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GruposController(ApplicationDbContext context)
        {
            _context = context;
        }



        // GET: Grupos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Grupos.ToListAsync());
        }

        // GET: Grupos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var grupo = await _context.Grupos
                .Include(g => g.ListaCategorias)
                .FirstOrDefaultAsync(g => g.Id == id);

            if (grupo == null) return NotFound();

            return View(grupo);
        }

        // GET: Grupos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Grupos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome")] Grupos grupo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(grupo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(grupo);
        }

        // GET: Grupos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var grupo = await _context.Grupos.FindAsync(id);
            if (grupo == null) return NotFound();

            return View(grupo);
        }

        // POST: Grupos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome")] Grupos grupo)
        {
            if (id != grupo.Id) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(grupo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GrupoExists(grupo.Id)) return NotFound();
                    else throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(grupo);
        }

        // GET: Grupos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var grupo = await _context.Grupos
                .Include(g => g.ListaCategorias)
                .FirstOrDefaultAsync(g => g.Id == id);

            if (grupo == null) return NotFound();

            return View(grupo);
        }

        // POST: Grupos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var grupo = await _context.Grupos
                .Include(g => g.ListaCategorias)
                .FirstOrDefaultAsync(g => g.Id == id);

            if (grupo != null && grupo.ListaCategorias.Any())
            {
                ModelState.AddModelError("", "Não é possível remover este grupo pois está associado a categorias.");
                return View(grupo);
            }

            if (grupo != null)
            {
                _context.Grupos.Remove(grupo);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        private bool GrupoExists(int id)
        {
            return _context.Grupos.Any(e => e.Id == id);
        }
    }
}

DWeb_MVC-master/DWeb_MVC/Views/Home/Index - Copy (2).cshtml
@{
    ViewBag.Title = "Home";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f8f9fa;
        }

        .navbar {
            margin-bottom: 20px;
        }

        .search-bar {
            margin-top: 20px;
        }

        .content {
            text-align: center;
            margin-top: 50px;
        }

            .content h1 {
                font-size: 3rem;
                font-weight: bold;
            }

            .content .list-group a {
                font-size: 1.2rem;
                color: #007bff;
            }

                .content .list-group a:hover {
                    text-decoration: none;
                    color: #0056b3;
                }

        .suggestions {
            z-index: 1000;
            width: 100%;
            background: white;
            border: 1px solid #ccc;
            border-radius: 0 0 4px 4px;
            max-height: 200px;
            overflow-y: auto;
            padding: 0;
            margin-top: -1px; /* Ensure the dropdown is right below the input field */
        }

            .suggestions li {
                padding: 10px;
                cursor: pointer;
                list-style: none; /* Remove list markers */
            }

                .suggestions li:hover {
                    background-color: #f8f9fa;
                }

        .input-group {
            position: relative; /* Ensure the input group is the reference for absolute positioning */
            width: 100%;
        }
    </style>
</head>
<body>
    <!-- Barra de Pesquisa -->
    @* <div class="container search-bar">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="input-group mb-3">
                    <input id="inputsearch" name="inputsearch" type="text" class="form-control" placeholder="Pesquisar produtos..." aria-label="Pesquisar produtos">
                </div>
                <ul id="listProd" class="suggestions" style="display: none;"></ul>
                <div id="search-results"></div> <!-- Container para resultados da busca -->
            </div>
        </div>
    </div> *@

    <!-- Conteúdo Principal -->
    <div class="container content">
        <h1>Gold Stirrup</h1>
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="list-group">
                    <a asp-controller="Produtos" asp-action="Index" class="list-group-item list-group-item-action">Ver catálogo</a>
                    <a asp-controller="Categorias" asp-action="Index" class="list-group-item list-group-item-action">Ver categorias</a>
                    <a asp-controller="Clientes" asp-action="Index" class="list-group-item list-group-item-action">Ver utilizadores</a>
                    <a asp-controller="Compras" asp-action="Index" class="list-group-item list-group-item-action">Ver compras</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Sobre nos -->
    <div class="container content">
        <div class="divContatoEmpresa">
            <h2>Informações de contacto</h2>
            <p>Morada: Rua cavaleiros de cristo, 34, Tomar</p>
            <p>Número de telefone: +351 938294618</p>
            <p>Email: info@goldsaddle.pt</p>
        </div>
    </div>


    <script>
                @*
        var products = @Html.Raw(Json.Serialize(Model.products));

        function updateProductList(products, input) {
            if (!Array.isArray(products)) {
                console.error('Products is not an array:', products);
                return;
            }

            const productList = document.getElementById('listProd');
            productList.innerHTML = ''; Limpa itens existentes
            if (input === "") {
                productList.style.display = 'none';
                return;
            }
            products.forEach(product => {
                if (product.Nome.toLowerCase().includes(input.toLowerCase())) { Corrigido para 'Nome'
                    const li = document.createElement('li');
                    li.onclick = function () {
                        location.href = "/Produtos/Details/" + product.Id; Corrigido para 'Id'
                    }
                    li.textContent = product.Nome; Corrigido para 'Nome'
                    productList.appendChild(li);
                }
            });
            productList.style.display = productList.children.length > 0 ? 'block' : 'none';
        }

        window.onload = function () {
            const searchInput = document.getElementById('inputsearch');
            searchInput.addEventListener('input', function () {
                updateProductList(products, searchInput.value);
            });*@
        };
        // var btnsearch = document.getElementById("search");
        // btnsearch.addEventListener("click", async (e) => {
        //     var inputsearch = document.getElementById("inputsearch");
        //     const response = await fetch(`/Produtos/Search/`, {
        //         method: 'GET',

        //     });

        //     if (response.ok) {
        //         const html = await response.text();
        //         document.getElementById('search-results').innerHTML = html;
        //     } else {
        //         console.error('HTTP error:', response.status);
        //     }
        // });
    </script>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

DWeb_MVC-master/DWeb_MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f8f9fa;
        }

        .navbar {
            margin-bottom: 20px;
        }

        .search-bar {
            margin-top: 20px;
        }

        .content {
            text-align: center;
            margin-top: 50px;
        }

            .content h1 {
                font-size: 3rem;
                font-weight: bold;
            }

            .content .list-group a {
                font-size: 1.2rem;
                color: #007bff;
            }

                .content .list-group a:hover {
                    text-decoration: none;
                    color: #0056b3;
                }

        .suggestions {
            z-index: 1000;
            width: 100%;
            background: white;
            border: 1px solid #ccc;
            border-radius: 0 0 4px 4px;
            max-height: 200px;
            overflow-y: auto;
            padding: 0;
            margin-top: -1px; /* Ensure the dropdown is right below the input field */
        }

            .suggestions li {
                padding: 10px;
                cursor: pointer;
                list-style: none; /* Remove list markers */
            }

                .suggestions li:hover {
                    background-color: #f8f9fa;
                }

        .input-group {
            position: relative; /* Ensure the input group is the reference for absolute positioning */
            width: 100%;
        }
    </style>
</head>
<body>
    <!-- Barra de Pesquisa -->
    @* <div class="container search-bar">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="input-group mb-3">
                    <input id="inputsearch" name="inputsearch" type="text" class="form-control" placeholder="Pesquisar produtos..." aria-label="Pesquisar produtos">
                </div>
                <ul id="listProd" class="suggestions" style="display: none;"></ul>
                <div id="search-results"></div> <!-- Container para resultados da busca -->
            </div>
        </div>
    </div> *@

    <!-- Conteúdo Principal -->
    <div class="container content">
        <h1 class="display-4 mb-5">Painel de Administração</h1>

        <!-- Secção 1: Gestão de Dados -->
        <h3 class="mb-3"> Gestão de Dados</h3>
        <div class="row">
            <div class="col-md-4 mb-4">
                <a asp-controller="Produtos" asp-action="Index" class="card shadow text-center p-4 h-100">
                    <h5 class="card-title"> Produtos</h5>
                    <p class="card-text">Adicionar e editar catálogo</p>
                </a>
            </div>
            <div class="col-md-4 mb-4">
                <a asp-controller="Categorias" asp-action="Index" class="card shadow text-center p-4 h-100">
                    <h5 class="card-title"> Categorias</h5>
                    <p class="card-text">Gerir categorias</p>
                </a>
            </div>
            <div class="col-md-4 mb-4">
                <a asp-controller="Grupos" asp-action="Index" class="card shadow text-center p-4 h-100">
                    <h5 class="card-title"> Grupos</h5>
                    <p class="card-text">Organizar categorias</p>
                </a>
            </div>
            <div class="col-md-4 mb-4">
                <a asp-controller="Cores" asp-action="Index" class="card shadow text-center p-4 h-100">
                    <h5 class="card-title"> Cores</h5>
                    <p class="card-text">Gerir cores dos produtos</p>
                </a>
            </div>
            <div class="col-md-4 mb-4">
                <a asp-controller="Tamanhos" asp-action="Index" class="card shadow text-center p-4 h-100">
                    <h5 class="card-title"> Tamanhos</h5>
                    <p class="card-text">Gerir tamanhos</p>
                </a>
            </div>
        </div>

        <!-- Secção 2: Consulta/Admin -->
        <h3 class="mt-5 mb-3"> Área de Consulta</h3>
        <div class="row">
            <div class="col-md-4 mb-4">
                <a asp-controller="Clientes" asp-action="Index" class="card bg-light shadow text-center p-4 h-100">
                    <h5 class="card-title"> Utilizadores</h5>
                    <p class="card-text">Visualizar e moderar utilizadores</p>
                </a>
            </div>
            <div class="col-md-4 mb-4">
                <a asp-controller="Compras" asp-action="Index" class="card bg-light shadow text-center p-4 h-100">
                    <h5 class="card-title"> Compras</h5>
                    <p class="card-text">Consultar histórico de compras</p>
                </a>
            </div>
        </div>
    </div>


    <!-- Sobre nos -->
    <div class="container content">
        <div class="divContatoEmpresa">
            <h2>Informações de contacto</h2>
            <p>Morada: Rua cavaleiros de cristo, 34, Tomar</p>
            <p>Número de telefone: +351 938294618</p>
            <p>Email: info@goldsaddle.pt</p>
        </div>
    </div>


    <script>
                @*
        var products = @Html.Raw(Json.Serialize(Model.products));

        function updateProductList(products, input) {
            if (!Array.isArray(products)) {
                console.error('Products is not an array:', products);
                return;
            }

            const productList = document.getElementById('listProd');
            productList.innerHTML = ''; Limpa itens existentes
            if (input === "") {
                productList.style.display = 'none';
                return;
            }
            products.forEach(product => {
                if (product.Nome.toLowerCase().includes(input.toLowerCase())) { Corrigido para 'Nome'
                    const li = document.createElement('li');
                    li.onclick = function () {
                        location.href = "/Produtos/Details/" + product.Id; Corrigido para 'Id'
                    }
                    li.textContent = product.Nome; Corrigido para 'Nome'
                    productList.appendChild(li);
                }
            });
            productList.style.display = productList.children.length > 0 ? 'block' : 'none';
        }

        window.onload = function () {
            const searchInput = document.getElementById('inputsearch');
            searchInput.addEventListener('input', function () {
                updateProductList(products, searchInput.value);
            });*@
        };
        // var btnsearch = document.getElementById("search");
        // btnsearch.addEventListener("click", async (e) => {
        //     var inputsearch = document.getElementById("inputsearch");
        //     const response = await fetch(`/Produtos/Search/`, {
        //         method: 'GET',

        //     });

        //     if (response.ok) {
        //         const html = await response.text();
        //         document.getElementById('search-results').innerHTML = html;
        //     } else {
        //         console.error('HTTP error:', response.status);
        //     }
        // });
    </script>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

DWeb_MVC-master/DWeb_MVC/Views/Home/Index1.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

DWeb_MVC-master/DWeb_MVC/Views/Home/Index2.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

DWeb_MVC-master/DWeb_MVC/Views/Home/Index3.cshtml
@page
@model DWeb_MVC.Views.Home.Index3Model
@{
}

DWeb_MVC-master/DWeb_MVC/Views/Home/Index4.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}