DWeb_MVC-master/DWeb_MVC/Controllers/CoresController.cs
using DWeb_MVC.Data;
using DWeb_MVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace DWeb_MVC.Controllers
{
    [Authorize(Roles = "admin")]

    public class CoresController : Controller
    {
        private readonly ApplicationDbContext _context;

        

        public CoresController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Cores.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var cor = await _context.Cores
                .Include(c => c.ListaProdutos)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (cor == null) return NotFound();

            return View(cor);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome")] Cores cor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cor);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var cor = await _context.Cores.FindAsync(id);
            if (cor == null) return NotFound();

            return View(cor);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome")] Cores cor)
        {
            if (id != cor.Id) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CoresExists(cor.Id)) return NotFound();
                    else throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cor);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var cor = await _context.Cores.FirstOrDefaultAsync(m => m.Id == id);
            if (cor == null) return NotFound();

            return View(cor);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cor = await _context.Cores
                .Include(c => c.ListaProdutos)
                .FirstOrDefaultAsync(c => c.Id == id);

            if (cor != null && cor.ListaProdutos.Any())
            {
                ModelState.AddModelError("", "Não é possível remover esta cor pois está associada a produtos.");
                return View(cor);
            }

            _context.Cores.Remove(cor);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CoresExists(int id)
        {
            return _context.Cores.Any(e => e.Id == id);
        }
    }
}

DWeb_MVC-master/DWeb_MVC/Controllers/GruposController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DWeb_MVC.Data;
using DWeb_MVC.Models;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Authorization;

namespace DWeb_MVC.Controllers
{
    [Authorize(Roles ="admin")]
    public class GruposController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GruposController(ApplicationDbContext context)
        {
            _context = context;
        }



        // GET: Grupos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Grupos.ToListAsync());
        }

        // GET: Grupos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var grupo = await _context.Grupos
                .Include(g => g.ListaCategorias)
                .FirstOrDefaultAsync(g => g.Id == id);

            if (grupo == null) return NotFound();

            return View(grupo);
        }

        // GET: Grupos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Grupos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome")] Grupos grupo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(grupo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(grupo);
        }

        // GET: Grupos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var grupo = await _context.Grupos.FindAsync(id);
            if (grupo == null) return NotFound();

            return View(grupo);
        }

        // POST: Grupos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome")] Grupos grupo)
        {
            if (id != grupo.Id) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(grupo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GrupoExists(grupo.Id)) return NotFound();
                    else throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(grupo);
        }

        // GET: Grupos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var grupo = await _context.Grupos
                .Include(g => g.ListaCategorias)
                .FirstOrDefaultAsync(g => g.Id == id);

            if (grupo == null) return NotFound();

            return View(grupo);
        }

        // POST: Grupos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var grupo = await _context.Grupos
                .Include(g => g.ListaCategorias)
                .FirstOrDefaultAsync(g => g.Id == id);

            if (grupo != null && grupo.ListaCategorias.Any())
            {
                ModelState.AddModelError("", "Não é possível remover este grupo pois está associado a categorias.");
                return View(grupo);
            }

            if (grupo != null)
            {
                _context.Grupos.Remove(grupo);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        private bool GrupoExists(int id)
        {
            return _context.Grupos.Any(e => e.Id == id);
        }
    }
}

DWeb_MVC-master/DWeb_MVC/Controllers/ProdutosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DWeb_MVC.Data;
using DWeb_MVC.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Filters;

namespace DWeb_MVC.Controllers
{
    [Authorize(Roles = "admin")]
    public class ProdutosController : Controller
    {
        private readonly ApplicationDbContext _bd;

        /// <summary>
        /// este recurso vai proporcionar acesso aos dados dos 
        /// recursos do servidor
        /// </summary>
        private readonly IWebHostEnvironment _webHostEnvironment;

        /*public override void OnActionExecuting(ActionExecutingContext context)
        {
            /*var email = context.HttpContext.User.Identity?.Name?.ToLower();
            if (email != "jose1@gmail.com")
            {
                context.Result = new RedirectToActionResult("UserHome", "Home", null);
            }

            base.OnActionExecuting(context);
        }*/


        public ProdutosController(
            ApplicationDbContext context,
            IWebHostEnvironment webHostEnvironment
            )
        {
            _bd = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Produtos
        public async Task<IActionResult> Index()
        {
            /* procurar, na base de dados, a lista dos produtos existentes
          * SELECT *
          * FROM Produtos a INNER JOIN Categoria c ON a.Categoria = c.Id
          */

            var listaProdutos = await _bd.Produtos
     .Include(p => p.Categoria)
         .ThenInclude(c => c.Grupos)
     .Include(p => p.Cores)
     .Include(p => p.Tamanhos)
     .Include(p => p.Fotos)
     .ToListAsync();

            return View(listaProdutos);
        }



        // GET: Produtos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _bd.Produtos == null)
            {
                return NotFound();
            }

            var produtos = await _bd.Produtos
                .Include(p => p.Categoria)
                .Include(p => p.Fotos)
                .Include(p => p.Cores)
                .Include(p => p.Tamanhos)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produtos == null)
            {
                return NotFound();
            }

            return View(produtos);
        }

        public async Task<IActionResult> Search(string id)
        {
            if (id == null || _bd.Produtos == null)
            {
                return NotFound();
            }

            var produtos = await _bd.Produtos
                .Include(p => p.Categoria)
                .Include(p => p.Fotos)
                .Include(p => p.Cores)
                .Include(p => p.Tamanhos)
                .FirstOrDefaultAsync(m => m.Nome.Equals(id));
            if (produtos == null)
            {
                return NotFound();
            }

            return View(produtos);
        }

        // GET: Produtos/Create
        public IActionResult Create()
        {
            // obter a lista de professores existentes na BD
            ViewData["ListaCat"] = _bd.Categorias.OrderBy(c => c.Nome).ToList();
            ViewData["ListaCores"] = _bd.Cores.OrderBy(c => c.Nome).ToList();
            ViewData["ListaTamanhos"] = _bd.Tamanhos.OrderBy(c => c.Nome).ToList();

            return View();
        }

        // POST: Produtos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Marca,Preco,PrecoAux")] Produtos produtos, int[] listaIdsCategorias, int[] listaIdsCores, int[] listaIdsTamanhos, IFormFile imagemProduto)
        {

            // Encontrar as categorias selecionadas e adicioná-las ao produto
            var listaCategorias = new List<Categorias>();
            foreach (var catId in listaIdsCategorias)
            {
                var cat = _bd.Categorias.FirstOrDefault(p => p.Id == catId);

                if (cat != null)
                {
                    listaCategorias.Add(cat);
                }
            }

            // Encontrar as cores selecionadas e adicioná-las ao produto

            var listaCores = new List<Cores>();
            foreach (var corId in listaIdsCores)
            {
                var cor = _bd.Cores.FirstOrDefault(c => c.Id == corId);
                if (cor != null)
                {
                    listaCores.Add(cor);
                }
            }
            produtos.Cores = listaCores;

            var listaTamanhos = new List<Tamanhos>();
            foreach (var tamanhoId in listaIdsTamanhos)
            {
                var tamanho = _bd.Tamanhos.FirstOrDefault(c => c.Id == tamanhoId);
                if (tamanho != null)
                {
                    listaTamanhos.Add(tamanho);
                }
            }
            produtos.Tamanhos = listaTamanhos;

            // vars. auxiliares
            string nomeFoto = "";
            bool existeFoto = false;

            // avaliar se temos condições para tentar adicionar o produto
            // testar se a Categoria do produto != 0 
            if (listaCategorias == null || listaCategorias.Count == 0)
            {
                ModelState.AddModelError("", "É obrigatório escolher uma Categoria.");
            }

            if (listaCores == null || listaCores.Count == 0)
            {
                ModelState.AddModelError("", "É obrigatório escolher pelo menos uma Cor.");
            }

            if (listaTamanhos == null || listaTamanhos.Count == 0)
            {
                ModelState.AddModelError("", "É obrigatório escolher pelo menos um Tamanho.");
            }

            // Apenas se ambas forem válidas, atribui
            if (ModelState.IsValid)
            {
                produtos.Categoria = listaCategorias;
                produtos.Cores = listaCores;
                produtos.Tamanhos = listaTamanhos;
                // se cheguei aqui, escolhi Categoria
                // será q escolhi Imagem? Vamos avaliar...

                if (imagemProduto == null)
                {
                    // o utilizador não fez upload de uma imagem
                    // vamos adicionar uma imagem prédefinida ao produto
                    produtos.Fotos
                            .Add(new Fotografias
                            {
                                Data = DateTime.Now,
                                Local = "NoImage",
                                NomeFicheiro = "noProduto.jpg"
                            });
                }
                else
                {
                    // há ficheiro. Mas, será que é uma imagem?
                    if (imagemProduto.ContentType != "image/jpeg" &&
                        imagemProduto.ContentType != "image/png")
                    {
                        //  <=>  ! (imagemProduto.ContentType == "image/jpeg" || imagemProduto.ContentType == "image/png")
                        // o ficheiro carregado não é uma imagem
                        // o que fazer?
                        // Vamos fazer o mesmo que quando o utilizador não
                        // fornece uma imagem
                        produtos.Fotos
                                .Add(new Fotografias
                                {
                                    Data = DateTime.Now,
                                    Local = "NoImage",
                                    NomeFicheiro = "noProduto.jpg"
                                });
                    }
                    else
                    {
                        // há imagem!!!
                        // determinar o nome da imagem
                        Guid g = Guid.NewGuid();
                        nomeFoto = g.ToString();
                        // obter a extensão do ficheiro
                        string extensaoNomeFoto = Path.GetExtension(imagemProduto.FileName).ToLower();
                        nomeFoto += extensaoNomeFoto;

                        // guardar os dados do ficheiro na BD
                        // para isso, vou associá-los ao 'produto'
                        produtos.Fotos
                                .Add(new Fotografias
                                {
                                    Data = DateTime.Now,
                                    Local = "",
                                    NomeFicheiro = nomeFoto
                                });

                        // informar a aplicação que há um ficheiro
                        // (imagem) para guardar no disco rígido
                        existeFoto = true;
                    }
                } // if (imagemProduto == null)
            } // if (produto.Categoria == 0)

            //atribuir os dados do PrecoAux ao Preco
            //se nao for nulo
            if (!string.IsNullOrEmpty(produtos.PrecoAux))
            {
                produtos.Preco = Convert.ToDecimal(produtos.PrecoAux.Replace('.', ','));
            }

            // se os dados recebidos respeitarem o modelo,
            // os dados podem ser adicionados
            if (ModelState.IsValid)
            {

                try
                {
                    // adicionar os dados à BD
                    _bd.Add(produtos);
                    // COMMIT da ação anterior
                    await _bd.SaveChangesAsync();

                    // se cheguei aqui, já foram guardados os dados
                    // do animal na BD. Já posso guardar a imagem
                    // no disco rígido do servidor

DWeb_MVC-master/DWeb_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DWeb_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DWeb_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                    <img src="~/imagens/logo.png" alt="Gold Stirrup" height="40" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Produtos" asp-action="Index">Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Categorias" asp-action="Index">Categorias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Grupos" asp-action="Index">Grupos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Cores" asp-action="Index">Cores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Tamanhos" asp-action="Index">Tamanhos</a>
                        </li>
                       
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Gold Stirrup - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DWeb_MVC-master/DWeb_MVC/Views/Shared/_LayoutPublic.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Loja Pública</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DWeb_MVC.styles.css" asp-append-version="true" />

    @{
        var currentAction = ViewContext.RouteData.Values["action"]?.ToString();
    }
    @if (currentAction == "UserHome")
    {
        <link rel="stylesheet" href="~/css/userhome.css" asp-append-version="true" />
    }


    @if (currentAction == "ProdutosPorCategoria" || currentAction == "ProdutosPorGrupo")
    {
        <link rel="stylesheet" href="~/css/CategoriaGrupo.css" asp-append-version="true" />
    }

    @if (currentAction == "Login" || currentAction == "Login")
    {
        <link rel="stylesheet" href="~/css/Site.css" asp-append-version="true" />
    }

   


</head>

<body>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 Loja Online - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>